=== NetrunnerDB/netrunner-cards-json/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "properties": {
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Faction id must be valid for the side.",
      "type": "object"
    },
    {
      "oneOf": [
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Type ids must be valid for the side.",
      "type": "object"
    }
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "faces": {
              "type": "null"
            },
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "maxItems": 1,
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "flip"
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "facade"
            }
          },
          "required": ["faces"]
        }
      ]
    }
  },
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["ice"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        },
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "designed_by": {
      "enum": ["fantasy_flight_games", "null_signal_games"],
      "minLength": 1,
      "type": "string"
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "is_unique": {
      "type": "boolean"
    },
    "layout_id": {
      "oneOf": [
        {
          "enum": ["normal", "flip", "copy", "facade", "progression"],
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "narrative_text": {
      "minLength": 0,
      "type": "string"
    },
    "pronouns": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_approx": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_ipa": {
      "minLength": 0,
      "type": "string"
    },
    "side_id": {
      "enum": ["corp", "runner"],
      "minLength": 1,
      "type": "string"
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "subtypes": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    }
  },
  "required": [
    "card_type_id",
    "deck_limit",
    "designed_by",
    "faction_id",
    "id",
    "is_unique",
    "side_id",
    "title"
  ],
  "type": "object"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/haarpsichord_studios_entertainment_unleashed.json
{
  "card_type_id": "corp_identity",
  "deck_limit": 1,
  "designed_by": "fantasy_flight_games",
  "faction_id": "nbn",
  "id": "haarpsichord_studios_entertainment_unleashed",
  "influence_limit": 15,
  "is_unique": false,
  "minimum_deck_size": 45,
  "side_id": "corp",
  "stripped_text": "The Runner cannot steal more than one agenda each turn.",
  "stripped_title": "Haarpsichord Studios: Entertainment Unleashed",
  "subtypes": ["division"],
  "text": "The Runner cannot steal more than one agenda each turn.",
  "title": "Haarpsichord Studios: Entertainment Unleashed"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/border_control.json
{
  "attribution": "Designed by 2016 World Champion Chris Dyer",
  "card_type_id": "ice",
  "cost": 4,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "weyland_consortium",
  "id": "border_control",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "corp",
  "strength": 1,
  "stripped_text": "trash: End the run. Use this ability only during a run on this server. Subroutine Gain 1 credit for each piece of ice protecting this server. Subroutine End the run.",
  "stripped_title": "Border Control",
  "subtypes": ["barrier"],
  "text": "[trash]: End the run. Use this ability only during a run on this server.\n[subroutine] Gain 1[credit] for each piece of ice protecting this server.\n[subroutine] End the run.",
  "title": "Border Control"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/airbladex_jsrf_ed.json
{
  "card_type_id": "hardware",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "shaper",
  "id": "airbladex_jsrf_ed",
  "influence_cost": 1,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "When you install this hardware, load 3 power counters onto it. When it is empty, trash it. Interrupt -> Hosted power counter: Prevent 1 net damage. Use this ability only during a run. Interrupt -> Hosted power counter: Prevent a \"when encountered\" ability on a piece of ice.",
  "stripped_title": "AirbladeX (JSRF Ed.)",
  "subtypes": ["vehicle"],
  "text": "When you install this hardware, load 3 power counters onto it. When it is empty, trash it.\n[interrupt] → <strong>Hosted power counter:</strong> Prevent 1 net damage. Use this ability only during a run.\n[interrupt] → <strong>Hosted power counter:</strong> Prevent a \"when encountered\" ability on a piece of ice.",
  "title": "AirbladeX (JSRF Ed.)"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/the_back.json
{
  "card_type_id": "resource",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "criminal",
  "id": "the_back",
  "influence_cost": 4,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "The first time each turn you use a piece of hardware during a run, place 1 power counter on this resource. click, remove this resource from the game: For each hosted power counter, choose up to 2 cards in your heap with trash abilities. Shuffle the chosen cards into your stack.",
  "stripped_title": "The Back",
  "subtypes": ["job", "location"],
  "text": "The first time each turn you use a piece of hardware during a run, place 1 power counter on this resource.\n[click], <strong>remove this resource from the game:</strong> For each hosted power counter, choose up to 2 cards in your heap with [trash] abilities. Shuffle the chosen cards into your stack.",
  "title": "The Back"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/cleaver.json
{
  "card_type_id": "program",
  "cost": 3,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "anarch",
  "id": "cleaver",
  "influence_cost": 2,
  "is_unique": false,
  "memory_cost": 1,
  "side_id": "runner",
  "strength": 3,
  "stripped_text": "Interface -> 1 credit: Break up to 2 barrier subroutines. 2 credits: +1 strength.",
  "stripped_title": "Cleaver",
  "subtypes": ["icebreaker", "fracter"],
  "text": "Interface â†’ <strong>1[credit]:</strong> Break up to 2 <strong>barrier</strong> subroutines.\n<strong>2[credit]:</strong> +1 strength.",
  "title": "Cleaver"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/compile.json
{
  "card_type_id": "event",
  "cost": 2,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "shaper",
  "id": "compile",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Make a run. The first time you encounter a piece of ice during this run, you may search your stack or heap for a program and install it, ignoring all costs. When the run ends, add that program to the bottom of your stack if it is still installed.",
  "stripped_title": "Compile",
  "subtypes": ["run"],
  "text": "Make a run. The first time you encounter a piece of ice during this run, you may search your stack or heap for a program and install it, ignoring all costs. When the run ends, add that program to the bottom of your stack if it is still installed.",
  "title": "Compile"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/blacklist.json
{
  "card_type_id": "asset",
  "cost": 0,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "nbn",
  "id": "blacklist",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "Cards cannot leave the Runner's heap for any reason.",
  "stripped_title": "Blacklist",
  "text": "Cards cannot leave the Runner's heap for any reason.",
  "title": "Blacklist",
  "trash_cost": 3
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/ngo_front.json
{
  "card_type_id": "asset",
  "cost": 0,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "neutral_corp",
  "id": "ngo_front",
  "influence_cost": 0,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "NGO Front can be advanced. trash,1 hosted advancement token: Gain 5 credits. trash,2 hosted advancement tokens: Gain 8 credits.",
  "stripped_title": "NGO Front",
  "text": "NGO Front can be advanced.\n[trash],<strong>1 hosted advancement token</strong>: Gain 5[credit].\n[trash],<strong>2 hosted advancement tokens</strong>: Gain 8[credit].",
  "title": "NGO Front",
  "trash_cost": 1
}
