=== NetrunnerDB/netrunner-cards-json/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "properties": {
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Faction id must be valid for the side.",
      "type": "object"
    },
    {
      "oneOf": [
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Type ids must be valid for the side.",
      "type": "object"
    }
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "faces": {
              "type": "null"
            },
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "maxItems": 1,
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "flip"
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "facade"
            }
          },
          "required": ["faces"]
        }
      ]
    }
  },
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["ice"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        },
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "designed_by": {
      "enum": ["fantasy_flight_games", "null_signal_games"],
      "minLength": 1,
      "type": "string"
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "is_unique": {
      "type": "boolean"
    },
    "layout_id": {
      "oneOf": [
        {
          "enum": ["normal", "flip", "copy", "facade", "progression"],
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "narrative_text": {
      "minLength": 0,
      "type": "string"
    },
    "pronouns": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_approx": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_ipa": {
      "minLength": 0,
      "type": "string"
    },
    "side_id": {
      "enum": ["corp", "runner"],
      "minLength": 1,
      "type": "string"
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "subtypes": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    }
  },
  "required": [
    "card_type_id",
    "deck_limit",
    "designed_by",
    "faction_id",
    "id",
    "is_unique",
    "side_id",
    "title"
  ],
  "type": "object"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/investigator_inez_delgado_4.json
{
  "card_type_id": "resource",
  "cost": 0,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "neutral_runner",
  "id": "investigator_inez_delgado_4",
  "influence_cost": 0,
  "is_unique": true,
  "layout_id": "normal",
  "side_id": "runner",
  "stripped_text": "Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points: Reveal each card in HQ and the top card of R&D. Use this only if you have stolean an agenda this turn.",
  "stripped_title": "Investigator Inez Delgado 4",
  "subtypes": ["connection"],
  "text": "<strong>Add Investigator Inez Delgado to your score area as an agenda worth 0 agenda points:</strong> Reveal each card in HQ and the top card of R&D. Use this only if you have stolean an agenda this turn.",
  "title": "Investigator Inez Delgado 4"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/adam_compulsive_hacker.json
{
  "base_link": 0,
  "card_type_id": "runner_identity",
  "deck_limit": 1,
  "designed_by": "fantasy_flight_games",
  "faction_id": "adam",
  "id": "adam_compulsive_hacker",
  "influence_limit": 25,
  "is_unique": false,
  "minimum_deck_size": 45,
  "side_id": "runner",
  "stripped_text": "You start the game with 3 different directive cards installed (these cards are not considered part of your deck).",
  "stripped_title": "Adam: Compulsive Hacker",
  "subtypes": ["bioroid"],
  "text": "You start the game with 3 different <strong>directive</strong> cards installed (these cards are not considered part of your deck).",
  "title": "Adam: Compulsive Hacker"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/tracker.json
{
  "card_type_id": "program",
  "cost": 0,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "criminal",
  "id": "tracker",
  "influence_cost": 2,
  "is_unique": false,
  "memory_cost": 2,
  "side_id": "runner",
  "stripped_text": "When your turn begins, you may choose a server. click, 2 credits: Run the chosen server. The first time a subroutine would resolve during that run, prevent it from resolving.",
  "stripped_title": "Tracker",
  "text": "When your turn begins, you may choose a server.\n<strong>[click]</strong>, <strong>2[credit]:</strong> Run the chosen server. The first time a subroutine would resolve during that run, prevent it from resolving.",
  "title": "Tracker"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/letheia_nisei.json
{
  "card_type_id": "upgrade",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "jinteki",
  "id": "letheia_nisei",
  "influence_cost": 3,
  "is_unique": true,
  "side_id": "corp",
  "stripped_text": "The first time the Runner approaches this server during each run, play a Psi Game. (Players secretly bid 0-2 credits. Then each player reveals and spends their bid.) If the bids differ, you may trash this upgrade. If you do, the Runner moves to the outermost position of this server. They may jack out.",
  "stripped_title": "Letheia Nisei",
  "subtypes": ["psi", "clone"],
  "text": "The first time the Runner approaches this server during each run, play a Psi Game. <em>(Players secretly bid 0â€“2[credit]. Then each player reveals and spends their bid.)</em> If the bids differ, you may trash this upgrade. If you do, the Runner moves to the outermost position of this server. They may jack out.",
  "title": "Letheia Nisei",
  "trash_cost": 2
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/gyri_labyrinth.json
{
  "card_type_id": "ice",
  "cost": 2,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "haas_bioroid",
  "id": "gyri_labyrinth",
  "influence_cost": 2,
  "is_unique": false,
  "side_id": "corp",
  "strength": 2,
  "stripped_text": "Subroutine The Runner's maximum hand size is reduced by 2 until the beginning of the Corp's next turn.",
  "stripped_title": "Gyri Labyrinth",
  "subtypes": ["code_gate"],
  "text": "[subroutine] The Runner's maximum hand size is reduced by 2 until the beginning of the Corp's next turn.",
  "title": "Gyri Labyrinth"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/anthill_excavation_contract.json
{
  "card_type_id": "asset",
  "cost": 3,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "weyland_consortium",
  "id": "anthill_excavation_contract",
  "influence_cost": 2,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "When you rez this asset, load 8 credits onto it. When it is empty, trash it. When your turn begins, take 4 credits from this asset and draw 1 card.",
  "stripped_title": "Anthill Excavation Contract",
  "subtypes": ["industrial"],
  "text": "When you rez this asset, load 8[credit] onto it. When it is empty, trash it.\nWhen your turn begins, take 4[credit] from this asset and draw 1 card.",
  "title": "Anthill Excavation Contract",
  "trash_cost": 1
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/luminal_transubstantiation.json
{
  "advancement_requirement": 3,
  "agenda_points": 2,
  "card_type_id": "agenda",
  "deck_limit": 1,
  "designed_by": "null_signal_games",
  "faction_id": "haas_bioroid",
  "id": "luminal_transubstantiation",
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "When you score this agenda, gain click click click. You cannot score agendas for the remainder of the turn. Limit 1 per deck.",
  "stripped_title": "Luminal Transubstantiation",
  "subtypes": ["research"],
  "text": "When you score this agenda, gain [click][click][click]. You cannot score agendas for the remainder of the turn.\nLimit 1 per deck.",
  "title": "Luminal Transubstantiation"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/rover_algorithm.json
{
  "card_type_id": "operation",
  "cost": 2,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "neutral_corp",
  "id": "rover_algorithm",
  "influence_cost": 0,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "Install Rover Algorithm on a rezzed piece of ice as a hosted condition counter with the text \"Host ice has +1 strength for each power counter on Rover Algorithm. Whenever the Runner passes host ice, place 1 power counter on Rover Algorithm.\"",
  "stripped_title": "Rover Algorithm",
  "text": "Install Rover Algorithm on a rezzed piece of ice as a hosted condition counter with the text \"Host ice has +1 strength for each power counter on Rover Algorithm. Whenever the Runner passes host ice, place 1 power counter on Rover Algorithm.\"",
  "title": "Rover Algorithm"
}
