=== NetrunnerDB/netrunner-cards-json/schema/v2/cards_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/cards_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "properties": {
            "faction_id": {
              "enum": [
                "haas_bioroid",
                "jinteki",
                "nbn",
                "neutral_corp",
                "weyland_consortium"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "faction_id": {
              "enum": [
                "adam",
                "anarch",
                "apex",
                "criminal",
                "neutral_runner",
                "shaper",
                "sunny_lebeau"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Faction id must be valid for the side.",
      "type": "object"
    },
    {
      "oneOf": [
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "agenda",
                "asset",
                "corp_identity",
                "ice",
                "operation",
                "upgrade"
              ]
            },
            "side_id": {
              "const": "corp"
            }
          }
        },
        {
          "properties": {
            "card_type_id": {
              "enum": [
                "event",
                "hardware",
                "program",
                "resource",
                "runner_identity"
              ]
            },
            "side_id": {
              "const": "runner"
            }
          }
        }
      ],
      "title": "Type ids must be valid for the side.",
      "type": "object"
    }
  ],
  "dependentSchemas": {
    "layout_id": {
      "oneOf": [
        {
          "properties": {
            "faces": {
              "type": "null"
            },
            "layout_id": {
              "oneOf": [
                {
                  "const": "normal"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "maxItems": 1,
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "flip"
            }
          },
          "required": ["faces"]
        },
        {
          "properties": {
            "faces": {
              "items": {
                "type": "object"
              },
              "minItems": 1,
              "type": "array"
            },
            "layout_id": {
              "const": "facade"
            }
          },
          "required": ["faces"]
        }
      ]
    }
  },
  "oneOf": [
    {
      "properties": {
        "advancement_requirement": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "agenda_points": {
          "minimum": 0,
          "type": "integer"
        },
        "card_type_id": {
          "const": "agenda"
        }
      },
      "required": ["advancement_requirement", "agenda_points"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["asset", "upgrade"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "trash_cost": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["ice"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "strength": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        },
        "cost": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "card_type_id": {
          "enum": ["corp_identity", "runner_identity"]
        },
        "influence_limit": {
          "oneOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "minimum_deck_size": {
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_requirement": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "attribution": {
      "minLength": 1,
      "type": "string"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "card_type_id": {
      "minLength": 1,
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "designed_by": {
      "enum": ["fantasy_flight_games", "null_signal_games"],
      "minLength": 1,
      "type": "string"
    },
    "faces": {
      "oneOf": [
        {
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "faction_id": {
      "minLength": 1,
      "type": "string"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "influence_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "is_unique": {
      "type": "boolean"
    },
    "layout_id": {
      "oneOf": [
        {
          "enum": ["normal", "flip", "copy", "facade", "progression"],
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "narrative_text": {
      "minLength": 0,
      "type": "string"
    },
    "pronouns": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_approx": {
      "minLength": 0,
      "type": "string"
    },
    "pronunciation_ipa": {
      "minLength": 0,
      "type": "string"
    },
    "side_id": {
      "enum": ["corp", "runner"],
      "minLength": 1,
      "type": "string"
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "subtypes": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    }
  },
  "required": [
    "card_type_id",
    "deck_limit",
    "designed_by",
    "faction_id",
    "id",
    "is_unique",
    "side_id",
    "title"
  ],
  "type": "object"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/personal_workshop.json
{
  "card_type_id": "resource",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "shaper",
  "id": "personal_workshop",
  "influence_cost": 4,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "click: Host a program or piece of hardware from your grip on Personal Workshop and place power counters on it equal to its install cost. 1 credit: Remove 1 power counter from a hosted card. When your turn begins, remove 1 power counter from a hosted card. When there are no power counters left on a hosted card, install it, ignoring all costs.",
  "stripped_title": "Personal Workshop",
  "subtypes": ["location"],
  "text": "[click]: Host a program or piece of hardware from your grip on Personal Workshop and place power counters on it equal to its install cost.\n1[credit]: Remove 1 power counter from a hosted card.\nWhen your turn begins, remove 1 power counter from a hosted card.\nWhen there are no power counters left on a hosted card, install it, ignoring all costs.",
  "title": "Personal Workshop"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/merger.json
{
  "advancement_requirement": 3,
  "agenda_points": 2,
  "card_type_id": "agenda",
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "neutral_corp",
  "id": "merger",
  "influence_cost": 1,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "Merger is worth 1 additional agenda point while in the Runner's score area.",
  "stripped_title": "Merger",
  "subtypes": ["expansion"],
  "text": "Merger is worth 1 additional agenda point while in the Runner's score area.",
  "title": "Merger"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/red_level_clearance.json
{
  "card_type_id": "operation",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "haas_bioroid",
  "id": "red_level_clearance",
  "influence_cost": 2,
  "is_unique": false,
  "side_id": "corp",
  "stripped_text": "Resolve 2 of the following in any order: * Draw 2 cards. * Gain 2 credits. * Install 1 non-agenda card from HQ. * Gain click.",
  "stripped_title": "Red Level Clearance",
  "subtypes": ["transaction"],
  "text": "Resolve 2 of the following in any order:<ul><li>Draw 2 cards.</li><li>Gain 2[credit].</li><li>Install 1 non-agenda card from HQ.</li><li>Gain [click].</li></ul>",
  "title": "Red Level Clearance"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/ghost_runner.json
{
  "card_type_id": "resource",
  "cost": 1,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "neutral_runner",
  "id": "ghost_runner",
  "influence_cost": 0,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Place 3 credits on Ghost Runner when it is installed. When there are no credits left on Ghost Runner, trash it. You can use the credits on Ghost Runner during a run.",
  "stripped_title": "Ghost Runner",
  "subtypes": ["stealth", "virtual"],
  "text": "Place 3[credit] on Ghost Runner when it is installed. When there are no credits left on Ghost Runner, trash it.\nYou can use the credits on Ghost Runner during a run.",
  "title": "Ghost Runner"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/orca.json
{
  "card_type_id": "program",
  "cost": 10,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "shaper",
  "id": "orca",
  "influence_cost": 2,
  "is_unique": false,
  "memory_cost": 2,
  "side_id": "runner",
  "strength": 3,
  "stripped_text": "The first time each turn this program fully breaks a piece of ice, you may charge 1 of your installed cards. (Add 1 power counter to a card that already has one.) Interface -> 2 credits: Break any number of sentry subroutines. 2 credits: +3 strength.",
  "stripped_title": "Orca",
  "subtypes": ["icebreaker", "killer"],
  "text": "The first time each turn this program fully breaks a piece of ice, you may charge 1 of your installed cards. <em>(Add 1 power counter to a card that already has one.)</em>\nInterface â†’ <strong>2[credit]:</strong> Break any number of <strong>sentry</strong> subroutines.\n<strong>2[credit]:</strong> +3 strength.",
  "title": "Orca"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/test_run.json
{
  "card_type_id": "event",
  "cost": 3,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "shaper",
  "id": "test_run",
  "influence_cost": 3,
  "is_unique": false,
  "side_id": "runner",
  "stripped_text": "Search either your stack or your heap for 1 program. (Shuffle your stack after searching it.) Install that program, ignoring all costs. When your turn ends, if that program has not been uninstalled, add it to the top of your stack.",
  "stripped_title": "Test Run",
  "text": "Search either your stack or your heap for 1 program. <em>(Shuffle your stack after searching it.)</em> Install that program, ignoring all costs. When your turn ends, if that program has not been uninstalled, add it to the top of your stack.",
  "title": "Test Run"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/boomerang.json
{
  "card_type_id": "hardware",
  "cost": 2,
  "deck_limit": 3,
  "designed_by": "null_signal_games",
  "faction_id": "criminal",
  "id": "boomerang",
  "influence_cost": 2,
  "is_unique": true,
  "side_id": "runner",
  "stripped_text": "When you install this hardware, choose 1 installed piece of ice. Use this hardware only during encounters with that ice. trash: Break up to 2 subroutines. When this run ends, if it was successful, you may shuffle 1 copy of Boomerang from your heap into your stack.",
  "stripped_title": "Boomerang",
  "text": "When you install this hardware, choose 1 installed piece of ice. Use this hardware only during encounters with that ice.\n<strong>[trash]:</strong> Break up to 2 subroutines. When this run ends, if it was successful, you may shuffle 1 copy of Boomerang from your heap into your stack.",
  "title": "Boomerang"
}

=== NetrunnerDB/netrunner-cards-json/v2/cards/ika.json
{
  "card_type_id": "program",
  "cost": 0,
  "deck_limit": 3,
  "designed_by": "fantasy_flight_games",
  "faction_id": "shaper",
  "id": "ika",
  "influence_cost": 2,
  "is_unique": false,
  "memory_cost": 1,
  "side_id": "runner",
  "strength": 2,
  "stripped_text": "2 credits: Host this program on a piece of ice. Interface -> 1 credit: Break up to 2 subroutines on host sentry. 2 credits: +3 strength.",
  "stripped_title": "Ika",
  "subtypes": ["icebreaker", "killer", "trojan"],
  "text": "<strong>2[credit]:</strong> Host this program on a piece of ice.\nInterface â†’ <strong>1[credit]:</strong> Break up to 2 subroutines on host <strong>sentry</strong>.\n<strong>2[credit]:</strong> +3 strength.",
  "title": "Ika"
}
