=== NetrunnerDB/netrunner-cards-json/schema/v2/printings_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/printings_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "items": {
    "additionalProperties": false,
    "dependentSchemas": {
      "layout_id": {
        "oneOf": [
          {
            "properties": {
              "faces": {
                "type": "null"
              },
              "layout_id": {
                "oneOf": [
                  {
                    "const": "normal"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          },
          {
            "properties": {
              "faces": {
                "items": {
                  "type": "object"
                },
                "maxItems": 1,
                "minItems": 1,
                "type": "array"
              },
              "layout_id": {
                "const": "flip"
              }
            },
            "required": ["faces"]
          },
          {
            "properties": {
              "faces": {
                "items": {
                  "type": "object"
                },
                "minItems": 1,
                "type": "array"
              },
              "layout_id": {
                "const": "copy"
              }
            },
            "required": ["faces"]
          },
          {
            "properties": {
              "faces": {
                "items": {
                  "type": "object"
                },
                "minItems": 1,
                "type": "array"
              },
              "layout_id": {
                "const": "facade"
              }
            },
            "required": ["faces"]
          }
        ]
      }
    },
    "properties": {
      "card_id": {
        "minLength": 1,
        "type": "string"
      },
      "card_set_id": {
        "minLength": 1,
        "type": "string"
      },
      "copy_quantity": {
        "minimum": 1,
        "type": "integer"
      },
      "faces": {
        "oneOf": [
          {
            "type": "array"
          },
          {
            "type": "null"
          }
        ]
      },
      "flavor": {
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "minLength": 1,
        "type": "string"
      },
      "illustrator": {
        "minLength": 1,
        "type": "string"
      },
      "layout_id": {
        "oneOf": [
          {
            "enum": ["normal", "flip", "copy", "facade", "progression"],
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "position": {
        "minimum": 1,
        "type": "integer"
      },
      "quantity": {
        "minimum": 1,
        "type": "integer"
      },
      "released_by": {
        "enum": ["fantasy_flight_games", "null_signal_games"],
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "card_id",
      "card_set_id",
      "id",
      "position",
      "quantity",
      "released_by"
    ],
    "type": "object"
  },
  "type": "array"
}

=== NetrunnerDB/netrunner-cards-json/v2/printings/station_one.json
[
  {
    "card_id": "severnius_stim_implant",
    "card_set_id": "station_one",
    "flavor": "\"Sure, the implantation was fine, but it pumps Burn. Did you think it wouldn't hurt?\"",
    "id": "12021",
    "illustrator": "Marius Bota",
    "position": 21,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "clan_vengeance",
    "card_set_id": "station_one",
    "flavor": "\"An eye for an eye? If you're lucky, that's all you'll lose.\"",
    "id": "12022",
    "illustrator": "Kate Laird",
    "position": 22,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "counter_surveillance",
    "card_set_id": "station_one",
    "flavor": "\"Who watches the watchers? We do.\"",
    "id": "12023",
    "illustrator": "Nasrul Hakim",
    "position": 23,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "mobius",
    "card_set_id": "station_one",
    "id": "12024",
    "illustrator": "Liiga Smilshkalne",
    "position": 24,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "los_data_hijacker",
    "card_set_id": "station_one",
    "flavor": "\"From code to profit in three easy steps.\"",
    "id": "12025",
    "illustrator": "Matt Zeilinger",
    "position": 25,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "system_seizure",
    "card_set_id": "station_one",
    "id": "12026",
    "illustrator": "Ethan Patrick Harris",
    "position": 26,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "customized_secretary",
    "card_set_id": "station_one",
    "id": "12027",
    "illustrator": "Liiga Smilshkalne",
    "position": 27,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "build_script",
    "card_set_id": "station_one",
    "flavor": "Sometimes efficiency is as easy as offloading routine work to a dedicated handler.",
    "id": "12028",
    "illustrator": "Ed Mattinian",
    "position": 28,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "seidr_adaptive_barrier",
    "card_set_id": "station_one",
    "id": "12029",
    "illustrator": "Michał Miłkowski",
    "position": 29,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "nerine_2_0",
    "card_set_id": "station_one",
    "flavor": "\"Submit.\"",
    "id": "12030",
    "illustrator": "Ethan Patrick Harris",
    "position": 30,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "load_testing",
    "card_set_id": "station_one",
    "flavor": "\"Trust me, most corps cannot match the performance of our brainmap enhanced system; a home-brewed rig doesn't stand a chance.\" - Rachel Giacomin",
    "id": "12031",
    "illustrator": "Ed Mattinian",
    "position": 31,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "bloom",
    "card_set_id": "station_one",
    "id": "12032",
    "illustrator": "Liiga Smilshkalne",
    "position": 32,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "replanting",
    "card_set_id": "station_one",
    "id": "12033",
    "illustrator": "Mark Molnar",
    "position": 33,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "cpc_generator",
    "card_set_id": "station_one",
    "flavor": "\"The customer pays to use our service, and then the advertisers pay us to put ads on their screens, and then the customers pay us a premium to remove the ads. Welcome to the dream.\"",
    "id": "12034",
    "illustrator": "Andreas Zafiratos",
    "position": 34,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "free_lunch",
    "card_set_id": "station_one",
    "id": "12035",
    "illustrator": "Adam S. Doyle",
    "position": 35,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "mca_informant",
    "card_set_id": "station_one",
    "id": "12036",
    "illustrator": "Limetown Studios",
    "position": 36,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "clyde_van_rite",
    "card_set_id": "station_one",
    "flavor": "\"You have two choices: do what I asked, or make me ask again. It's your choice, but if I have to ask again, it will go badly for you.\"",
    "id": "12037",
    "illustrator": "Anna Edwards",
    "position": 37,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "watchtower",
    "card_set_id": "station_one",
    "flavor": "416d20472046204720416d",
    "id": "12038",
    "illustrator": "BalanceSheet",
    "position": 38,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "sacrifice",
    "card_set_id": "station_one",
    "id": "12039",
    "illustrator": "Martin de Diego Sádaba",
    "position": 39,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  },
  {
    "card_id": "self_adapting_code_wall",
    "card_set_id": "station_one",
    "flavor": "\"All my best tricks were shrugged right off. I ended up having to send a self-destruct code to the whole server.\" - Wyvern",
    "id": "12040",
    "illustrator": "Shawn Ye Zhongyi",
    "position": 40,
    "quantity": 3,
    "released_by": "fantasy_flight_games"
  }
]
