=== NetrunnerDB/netrunner-cards-json/schema/v2/restrictions_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/restrictions_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "banned": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "type": "array"
    },
    "date_start": {
      "minLength": 1,
      "type": "string"
    },
    "format_id": {
      "minLength": 1,
      "type": "string"
    },
    "global_penalty": {
      "properties": {
        "1": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "name": {
      "minLength": 1,
      "type": "string"
    },
    "point_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "points": {
      "properties": {
        "1": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "2": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "3": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "restricted": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "type": "array"
    },
    "subtypes": {
      "properties": {
        "banned": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "universal_faction_cost": {
      "properties": {
        "1": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "3": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    }
  },
  "required": ["id", "name", "date_start", "format_id"],
  "type": "object"
}

=== NetrunnerDB/netrunner-cards-json/v2/restrictions/standard/standard_mwl_3_4_b.json
{
  "banned": [
    "24_7_news_cycle",
    "aaron_marron",
    "bloo_moose",
    "bryan_stinson",
    "clone_suffrage_movement",
    "crowdfunding",
    "employee_strike",
    "faust",
    "friends_in_high_places",
    "gpi_net_tap",
    "hired_help",
    "hyperdriver",
    "jinteki_potential_unleashed",
    "laamb",
    "liza_talking_thunder_prominent_legislator",
    "mars_for_martians",
    "mti_mwekundu_life_improved",
    "mumbad_city_hall",
    "museum_of_history",
    "salvaged_vanadis_armory",
    "sensie_actors_union",
    "sifr",
    "tapwrm",
    "temujin_contract",
    "watch_the_world_burn",
    "zealous_judge",
    "zer0"
  ],
  "date_start": "2019-12-31",
  "format_id": "standard",
  "id": "standard_mwl_3_4_b",
  "name": "Standard MWL 3.4b",
  "restricted": [
    "aesops_pawnshop",
    "bio_ethics_association",
    "corporate_grant",
    "dorm_computer",
    "engolo",
    "film_critic",
    "gang_sign",
    "global_food_initiative",
    "inversificator",
    "labor_rights",
    "mad_dash",
    "mumba_temple",
    "obokata_protocol",
    "paperclip",
    "rumor_mill",
    "tech_trader",
    "whampoa_reclamation"
  ]
}

=== NetrunnerDB/netrunner-cards-json/v2/restrictions/standard/standard_mwl_3_0.json
{
  "id": "standard_mwl_3_0",
  "name": "Standard MWL 3.0",
  "date_start": "2018-12-21",
  "format_id": "standard",
  "restricted": [
    "aesops_pawnshop",
    "bio_ethics_association",
    "commercial_bankers_group",
    "employee_strike",
    "excalibur",
    "film_critic",
    "gang_sign",
    "global_food_initiative",
    "inversificator",
    "jinteki_potential_unleashed",
    "levy_ar_lab_access",
    "mad_dash",
    "mother_goddess",
    "mti_mwekundu_life_improved",
    "mumba_temple",
    "mumbad_city_hall",
    "obokata_protocol",
    "paperclip",
    "rumor_mill",
    "surveyor",
    "violet_level_clearance",
    "whampoa_reclamation"
  ],
  "banned": [
    "24_7_news_cycle",
    "aaron_marron",
    "bloo_moose",
    "bryan_stinson",
    "cerebral_imaging_infinite_frontiers",
    "clone_suffrage_movement",
    "faust",
    "friends_in_high_places",
    "hired_help",
    "hyperdriver",
    "mars_for_martians",
    "museum_of_history",
    "salvaged_vanadis_armory",
    "sensie_actors_union",
    "sifr",
    "tapwrm",
    "temujin_contract",
    "watch_the_world_burn",
    "zer0"
  ]
}

=== NetrunnerDB/netrunner-cards-json/v2/restrictions/standard/standard_ban_list_21_06.json
{
  "banned": [
    "24_7_news_cycle",
    "aaron_marron",
    "another_day_another_paycheck",
    "azmari_edtech_shaping_the_future",
    "bloo_moose",
    "breached_dome",
    "bryan_stinson",
    "cayambe_grid",
    "cerebral_static",
    "clan_vengeance",
    "clone_suffrage_movement",
    "clones_are_not_people",
    "corporate_grant",
    "corporate_scandal",
    "crowdfunding",
    "death_and_taxes",
    "defective_brainchips",
    "door_to_door",
    "employee_strike",
    "encore",
    "enforced_curfew",
    "engram_flush",
    "enhanced_login_protocol",
    "fairchild_3_0",
    "freedom_through_equality",
    "friends_in_high_places",
    "gagarin_deep_space_expanding_the_horizon",
    "game_changer",
    "gold_farmer",
    "government_investigations",
    "government_takeover",
    "gpi_net_tap",
    "hacktivist_meeting",
    "hired_help",
    "housekeeping",
    "interdiction",
    "itinerant_protesters",
    "jinteki_potential_unleashed",
    "kakugo",
    "kill_switch",
    "laamb",
    "lag_time",
    "liza_talking_thunder_prominent_legislator",
    "mad_dash",
    "manhunt",
    "mars_for_martians",
    "mass_commercialization",
    "media_blitz",
    "mti_mwekundu_life_improved",
    "mumbad_city_hall",
    "museum_of_history",
    "net_celebrity",
    "pad_tap",
    "paywall_implementation",
    "predictive_algorithm",
    "rolling_brownout",
    "rumor_mill",
    "salvaged_vanadis_armory",
    "scarcity_of_resources",
    "scrubbed",
    "sensie_actors_union",
    "service_outage",
    "shipment_from_tennin",
    "sifr",
    "slot_machine",
    "ssl_endorsement",
    "surveillance_sweep",
    "system_outage",
    "system_seizure",
    "targeted_marketing",
    "temujin_contract",
    "titan_transnational_investing_in_your_future",
    "traffic_jam",
    "unscheduled_maintenance",
    "violet_level_clearance",
    "watch_the_world_burn",
    "whampoa_reclamation",
    "zealous_judge"
  ],
  "date_start": "2021-06-19",
  "format_id": "standard",
  "id": "standard_ban_list_21_06",
  "name": "Standard Ban List 21.06",
  "subtypes": {
    "banned": ["current"]
  }
}
