=== NetrunnerDB/netrunner-cards-json/schema/card_schema.json
{
  "$id": "https://github.com/Alsciende/netrunner-cards-json/blob/master/schema/card_schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "oneOf": [
    {
      "properties": {
        "type_code": {
          "const": "agenda"
        }
      },
      "required": ["advancement_cost", "agenda_points"]
    },
    {
      "properties": {
        "type_code": {
          "enum": ["asset", "upgrade"]
        }
      },
      "required": ["cost", "trash_cost"]
    },
    {
      "properties": {
        "type_code": {
          "enum": ["ice"]
        }
      },
      "required": ["cost", "strength"]
    },
    {
      "properties": {
        "type_code": {
          "enum": ["event", "hardware", "operation", "program", "resource"]
        }
      },
      "required": ["cost"]
    },
    {
      "properties": {
        "type_code": {
          "const": "identity"
        }
      },
      "required": ["influence_limit", "minimum_deck_size"]
    }
  ],
  "properties": {
    "advancement_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "agenda_points": {
      "minimum": 0,
      "type": "integer"
    },
    "base_link": {
      "minimum": 0,
      "type": "integer"
    },
    "code": {
      "pattern": "^[0-9]{5}$",
      "type": "string"
    },
    "cost": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "deck_limit": {
      "minimum": 1,
      "type": "integer"
    },
    "faction_code": {
      "minLength": 1,
      "type": "string"
    },
    "faction_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "flavor": {
      "minLength": 1,
      "type": "string"
    },
    "illustrator": {
      "pattern": ".+",
      "type": "string"
    },
    "influence_limit": {
      "oneOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "keywords": {
      "minLength": 1,
      "type": "string"
    },
    "memory_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "minimum_deck_size": {
      "minimum": 0,
      "type": "integer"
    },
    "pack_code": {
      "maxLength": 5,
      "minLength": 2,
      "type": "string"
    },
    "position": {
      "minimum": 1,
      "type": "integer"
    },
    "quantity": {
      "minimum": 1,
      "type": "integer"
    },
    "side_code": {
      "minLength": 1,
      "type": "string"
    },
    "strength": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ]
    },
    "stripped_text": {
      "minLength": 1,
      "type": "string"
    },
    "stripped_title": {
      "minLength": 1,
      "type": "string"
    },
    "text": {
      "minLength": 1,
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    },
    "trash_cost": {
      "minimum": 0,
      "type": "integer"
    },
    "type_code": {
      "minLength": 1,
      "type": "string"
    },
    "uniqueness": {
      "type": "boolean"
    }
  },
  "required": [
    "code",
    "faction_code",
    "deck_limit",
    "pack_code",
    "position",
    "quantity",
    "side_code",
    "title",
    "type_code",
    "uniqueness"
  ],
  "type": "object"
}

=== NetrunnerDB/netrunner-cards-json/pack/in.json
[
  {
    "code": "11061",
    "cost": 0,
    "deck_limit": 3,
    "faction_code": "anarch",
    "faction_cost": 2,
    "flavor": "\"When your opponent is weak, strike. If you do not, he will become strong.\" - the Playbook",
    "illustrator": "Lili Ibrahim",
    "keywords": "Sabotage",
    "pack_code": "in",
    "position": 61,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "Play only if you made a successful run this turn. Trash 1 unrezzed piece of ice you passed during your last run.",
    "stripped_title": "En Passant",
    "text": "Play only if you made a successful run this turn.\nTrash 1 unrezzed piece of ice you passed during your last run.",
    "title": "En Passant",
    "type_code": "event",
    "uniqueness": false
  },
  {
    "code": "11062",
    "cost": 3,
    "deck_limit": 3,
    "faction_code": "anarch",
    "faction_cost": 3,
    "flavor": "Omar goes through four, five keyboards per week, no two from the same decade.",
    "illustrator": "Nasrul Hakim",
    "pack_code": "in",
    "position": 62,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "Look at the top 10 cards of your stack. If any of those cards are programs, you may install one of them, lowering the install cost by 5. Trash the rest of those cards.",
    "stripped_title": "Frantic Coding",
    "text": "Look at the top 10 cards of your stack. If any of those cards are programs, you may install one of them, lowering the install cost by 5. Trash the rest of those cards.",
    "title": "Frantic Coding",
    "type_code": "event",
    "uniqueness": false
  },
  {
    "code": "11063",
    "cost": 5,
    "deck_limit": 3,
    "faction_code": "criminal",
    "faction_cost": 1,
    "illustrator": "Del Borovic",
    "keywords": "Console",
    "pack_code": "in",
    "position": 63,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "+2 mu Whenever you breach HQ during a run, access 1 additional card for each piece of ice protecting HQ that you fully broke during that run. Limit 1 console per player.",
    "stripped_title": "The Gauntlet",
    "text": "+2[mu]\nWhenever you breach HQ during a run, access 1 additional card for each piece of ice protecting HQ that you fully broke during that run.\nLimit 1 <strong>console</strong> per player.",
    "title": "The Gauntlet",
    "type_code": "hardware",
    "uniqueness": true
  },
  {
    "code": "11064",
    "cost": 4,
    "deck_limit": 3,
    "faction_code": "criminal",
    "faction_cost": 2,
    "flavor": "Spiraling even higher, every feature of cyberspace sprawled before it.",
    "illustrator": "Liiga Smilshkalne",
    "keywords": "Icebreaker - Fracter",
    "memory_cost": 1,
    "pack_code": "in",
    "position": 64,
    "quantity": 3,
    "side_code": "runner",
    "strength": 1,
    "stripped_text": "Interface -> 1 credit: Break 1 barrier subroutine. 2 credits: +2 strength. 2 credits, add this program to your grip: Derez 1 barrier this program fully broke during this encounter.",
    "stripped_title": "Saker",
    "text": "Interface → <strong>1[credit]:</strong> Break 1 <strong>barrier</strong> subroutine.\n<strong>2[credit]:</strong> +2 strength.\n<strong>2[credit]</strong>, <strong>add this program to your grip:</strong> Derez 1 <strong>barrier</strong> this program fully broke during this encounter.",
    "title": "Saker",
    "type_code": "program",
    "uniqueness": false
  },
  {
    "code": "11065",
    "cost": 1,
    "deck_limit": 3,
    "faction_code": "criminal",
    "faction_cost": 1,
    "flavor": "\"I used to run stims, simsensies, the usual. I was scum. Now I run water. I'm a fragging hero.\"",
    "illustrator": "Chris Peuler",
    "keywords": "Connection",
    "pack_code": "in",
    "position": 65,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "click,click: Draw 3 cards. Shuffle 1 card from your grip into your stack.",
    "stripped_title": "Blockade Runner",
    "text": "[click],[click]: Draw 3 cards. Shuffle 1 card from your grip into your stack.",
    "title": "Blockade Runner",
    "type_code": "resource",
    "uniqueness": false
  },
  {
    "base_link": 0,
    "code": "11066",
    "deck_limit": 1,
    "faction_code": "shaper",
    "flavor": "\"Nothing up my sleeve...\"",
    "illustrator": "Matt Zeilinger",
    "influence_limit": 15,
    "keywords": "G-mod - Stealth",
    "minimum_deck_size": 40,
    "pack_code": "in",
    "position": 66,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "1 recurring credit Use this credit to pay for using icebreakers.",
    "stripped_title": "Ele \"Smoke\" Scovak: Cynosure of the Net",
    "text": "1[recurring-credit]\nUse this credit to pay for using <strong>icebreakers</strong>.",
    "title": "Ele \"Smoke\" Scovak: Cynosure of the Net",
    "type_code": "identity",
    "uniqueness": false
  },
  {
    "code": "11067",
    "cost": 0,
    "deck_limit": 3,
    "faction_code": "shaper",
    "faction_cost": 1,
    "flavor": "\"I usually find something interesting in there. Just not what I was looking for.\"",
    "illustrator": "John Ariosa",
    "pack_code": "in",
    "position": 67,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "Whenever you make a successful run on R&D, instead of breaching R&D, you may choose 1 of the top 5 cards in R&D and access it.",
    "stripped_title": "Top Hat",
    "text": "Whenever you make a successful run on R&D, instead of breaching R&D, you may choose 1 of the top 5 cards in R&D and access it.",
    "title": "Top Hat",
    "type_code": "hardware",
    "uniqueness": false
  },
  {
    "code": "11068",
    "cost": 4,
    "deck_limit": 3,
    "faction_code": "shaper",
    "faction_cost": 2,
    "flavor": "The personality must be bigger than the prop.",
    "illustrator": "Seage",
    "keywords": "Icebreaker - Fracter",
    "memory_cost": 1,
    "pack_code": "in",
    "position": 68,
    "quantity": 3,
    "side_code": "runner",
    "strength": 3,
    "stripped_text": "Interface -> 1 credit: Break 1 barrier subroutine. 3 credits: +4 strength for the remainder of this run. Use this ability only by spending at least 1 credit from a stealth card.",
    "stripped_title": "Blackstone",
    "text": "Interface → <strong>1[credit]:</strong> Break 1 <strong>barrier</strong> subroutine.\n<strong>3[credit]:</strong> +4 strength for the remainder of this run. Use this ability only by spending at least 1[credit] from a <strong>stealth</strong> card.",
    "title": "Blackstone",
    "type_code": "program",
    "uniqueness": false
  },
  {
    "code": "11069",
    "cost": 0,
    "deck_limit": 3,
    "faction_code": "neutral-runner",
    "faction_cost": 0,
    "flavor": "\"Take this to Inez Delgado in Netcrimes. No one else.\"",
    "illustrator": "Leanna Crossan",
    "keywords": "Current",
    "pack_code": "in",
    "position": 69,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "This card is not trashed until another current is played or an agenda is scored. While secretly spending credits, players cannot spend 2 credits.",
    "stripped_title": "Government Investigations",
    "text": "This card is not trashed until another <strong>current</strong> is played or an agenda is scored.\nWhile secretly spending credits, players cannot spend 2[credit].",
    "title": "Government Investigations",
    "type_code": "event",
    "uniqueness": false
  },
  {
    "code": "11070",
    "cost": 2,
    "deck_limit": 3,
    "faction_code": "neutral-runner",
    "faction_cost": 0,
    "flavor": "\"The Starlight Meditation Booths are available to refugees for free for the duration of the crisis.\"",
    "illustrator": "Maciej Rebisz",
    "keywords": "Location",
    "pack_code": "in",
    "position": 70,
    "quantity": 3,
    "side_code": "runner",
    "stripped_text": "If you are tagged when your turn ends, force the Corp to \"Trace 1 If unsuccessful, the Runner removes 1 tag.\" trash,trash all cards in your grip: Prevent all meat damage.",
    "stripped_title": "Citadel Sanctuary",
    "text": "If you are tagged when your turn ends, force the Corp to \"<trace>Trace 1</trace> If unsuccessful, the Runner removes 1 tag.\"\n[trash],<strong>trash all cards in your grip:</strong> Prevent all meat damage.",
    "title": "Citadel Sanctuary",
    "type_code": "resource",
    "uniqueness": true
  },
  {
    "code": "11071",
    "cost": 1,
    "deck_limit": 3,
    "faction_code": "haas-bioroid",
    "faction_cost": 2,
    "flavor": "\"I let the bioroids do a ride-along via remote, so they can see what pain really looks like.\" -Agent Valkyrie",
    "illustrator": "Antonio De Luca",
    "keywords": "Condition",
    "pack_code": "in",
    "position": 71,
    "quantity": 3,
    "side_code": "corp",
    "stripped_text": "Install Wetwork Refit on a rezzed piece of bioroid ice as a condition counter with the text \"Host ice gains \"Subroutine Do 1 brain damage.\" before all its other subroutines.\"",
    "stripped_title": "Wetwork Refit",
    "text": "Install Wetwork Refit on a rezzed piece of <strong>bioroid</strong> ice as a condition counter with the text \"Host ice gains \"[subroutine] Do 1 brain damage.\" before all its other subroutines.\"",
    "title": "Wetwork Refit",
    "type_code": "operation",
    "uniqueness": false
  },
  {
    "code": "11072",
    "deck_limit": 1,
    "faction_code": "haas-bioroid",
    "influence_limit": 12,
    "keywords": "Megacorp",
    "minimum_deck_size": 45,
    "pack_code": "in",
    "position": 72,
    "quantity": 3,
    "side_code": "corp",
    "stripped_text": "The first time each turn the Runner passes a rezzed piece of bioroid ice, you may rez 1 bioroid card, paying 4 credits less.",
    "stripped_title": "Haas-Bioroid: Architects of Tomorrow",
    "text": "The first time each turn the Runner passes a rezzed piece of <strong>bioroid</strong> ice, you may rez 1 <strong>bioroid</strong> card, paying 4[credit] less.",
    "title": "Haas-Bioroid: Architects of Tomorrow",
